version: 0.0
os: linux
files:
  - source: /backend/
    destination: /var/MaxCard/
hooks:
  AfterInstall:
    - location: scripts/install_dependencies.sh
      timeout: 300
      runas: root
  ApplicationStart:
    - location: scripts/start_server.sh
      timeout: 300
      runas: root
